# Generated by Django 4.2.2 on 2023-07-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_alter_disciplina_professores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='professores',
            field=models.ManyToManyField(related_name='disciplina', to='portfolio.pessoa'),
        ),
    ]
