# Generated by Django 4.2.2 on 2023-07-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='link',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
