# Generated by Django 4.2.2 on 2023-07-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
