# Generated by Django 4.2.2 on 2023-07-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_post_deslikes_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comentario',
            field=models.ManyToManyField(related_name='posts', to='portfolio.comment'),
        ),
    ]
