# Generated by Django 4.2.2 on 2023-07-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_post_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='area',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
