# Generated by Django 4.2.2 on 2023-07-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0029_remove_projects_advisors_projects_professores_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='projects',
            name='professores',
        ),
        migrations.AddField(
            model_name='projects',
            name='advisors',
            field=models.ManyToManyField(related_name='projects', to='portfolio.advisor'),
        ),
    ]
