# Generated by Django 4.2.2 on 2023-07-19 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0034_praia_regiao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regiao',
            name='praia',
        ),
        migrations.AddField(
            model_name='regiao',
            name='praia',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='portfolio.praia'),
            preserve_default=False,
        ),
    ]
