# Generated by Django 4.2.2 on 2023-07-19 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0035_remove_regiao_praia_regiao_praia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regiao',
            name='praia',
        ),
        migrations.AddField(
            model_name='praia',
            name='regiao',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='portfolio.regiao'),
            preserve_default=False,
        ),
    ]
