# Generated by Django 4.2.2 on 2023-07-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0036_remove_regiao_praia_praia_regiao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='praia',
            name='regiao',
        ),
        migrations.AddField(
            model_name='regiao',
            name='praia',
            field=models.ManyToManyField(related_name='regiao', to='portfolio.praia'),
        ),
    ]
